/* Daybook — one quote for each day of the year, indexed by day of year
   (entry 0 is 1 January, entry 365 is 31 December in a leap year).
   Format: [quote, author]. Edit freely; keep 366 entries so no day repeats. */
window.DAYBOOK_QUOTES = [
  ["Begin at once to live, and count each separate day as a separate life.", "Seneca"],
  ["One swallow does not make a summer, nor does one day.", "Aristotle"],
  ["No one is laughable who laughs at himself.", "Seneca"],
  ["Insist on yourself; never imitate.", "Ralph Waldo Emerson"],
  ["Take rest; a field that has rested gives a bountiful crop.", "Ovid"],
  ["As long as you live, keep learning how to live.", "Seneca"],
  ["You may encounter many defeats, but you must not be defeated.", "Maya Angelou"],
  ["Anyone can hold the helm when the sea is calm.", "Publilius Syrus"],
  ["To have faults and not to reform them — this, indeed, is to have faults.", "Confucius"],
  ["Dwell on the beauty of life. Watch the stars, and see yourself running with them.", "Marcus Aurelius"],
  ["Never suffer an exception to occur till the new habit is securely rooted in your life.", "William James"],
  ["We suffer more often in imagination than in reality.", "Seneca"],
  ["They are new every morning.", "Lamentations 3:23"],
  ["Weeping may endure for a night, but joy cometh in the morning.", "Psalm 30:5"],
  ["It is good to have an end to journey toward; but it is the journey that matters, in the end.", "Ursula K. Le Guin"],
  ["Make the best use of what is in your power, and take the rest as it happens.", "Epictetus"],
  ["Seize the very first possible opportunity to act on every resolution you make.", "William James"],
  ["No man was ever wise by chance.", "Seneca"],
  ["The beginning is the most important part of the work.", "Plato"],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant"],
  ["Be like the promontory against which the waves continually break, but it stands firm and tames the fury of the water around it.", "Marcus Aurelius"],
  ["Until we have begun to go without them, we fail to realize how unnecessary many things are.", "Seneca"],
  ["Have patience with all things, but first of all with yourself.", "Francis de Sales"],
  ["A journey of a thousand miles begins with a single step.", "Lao Tzu"],
  ["Nature has given us the seeds of knowledge, not knowledge itself.", "Seneca"],
  ["Say nothing more to yourself than what the first appearances report.", "Marcus Aurelius"],
  ["The first principle is that you must not fool yourself — and you are the easiest person to fool.", "Richard Feynman"],
  ["He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.", "Proverbs 16:32"],
  ["Make each day your masterpiece.", "John Wooden"],
  ["All cruelty springs from weakness.", "Seneca"],
  ["This above all: to thine own self be true.", "William Shakespeare"],
  ["The art of being wise is the art of knowing what to overlook.", "William James"],
  ["Health is the greatest of gifts, contentment the greatest of riches.", "The Dhammapada"],
  ["Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.", "Ecclesiastes 7:8"],
  ["Neither should a ship rely on one small anchor, nor should life rest on a single hope.", "Epictetus"],
  ["The years teach much which the days never know.", "Ralph Waldo Emerson"],
  ["The fault, dear Brutus, is not in our stars, but in ourselves.", "William Shakespeare"],
  ["Do not spoil what you have by desiring what you have not.", "Epicurus"],
  ["Things won are done; joy's soul lies in the doing.", "William Shakespeare"],
  ["Real generosity toward the future lies in giving all to the present.", "Albert Camus"],
  ["Nothing is so bitter that a calm mind cannot find comfort in it.", "Seneca"],
  ["Smile, breathe, and go slowly.", "Thich Nhat Hanh"],
  ["Everywhere means nowhere.", "Seneca"],
  ["Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.", "Matthew 6:34"],
  ["All we have to decide is what to do with the time that is given us.", "J.R.R. Tolkien"],
  ["The credit belongs to the man who is actually in the arena.", "Theodore Roosevelt"],
  ["Be not simply good; be good for something.", "Henry David Thoreau"],
  ["Those who know do not speak; those who speak do not know.", "Lao Tzu"],
  ["Character is destiny.", "Heraclitus"],
  ["Nothing in life is to be feared, it is only to be understood.", "Marie Curie"],
  ["In the midst of winter, I found there was, within me, an invincible summer.", "Albert Camus"],
  ["Forever is composed of nows.", "Emily Dickinson"],
  ["How we spend our days is, of course, how we spend our lives.", "Annie Dillard"],
  ["Little strokes fell great oaks.", "Benjamin Franklin"],
  ["Keep your face to the sunshine and you cannot see a shadow.", "Helen Keller"],
  ["Nothing, Lucilius, is ours, except time.", "Seneca"],
  ["That it will never come again is what makes life so sweet.", "Emily Dickinson"],
  ["Let everything happen to you: beauty and terror. Just keep going. No feeling is final.", "Rainer Maria Rilke"],
  ["Confine yourself to the present.", "Marcus Aurelius"],
  ["Everything I know, I know because of love.", "Leo Tolstoy"],
  ["No one can live happily who has regard to himself alone.", "Seneca"],
  ["If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"],
  ["If you have a garden and a library, you have everything you need.", "Cicero"],
  ["He who fears he shall suffer, already suffers what he fears.", "Michel de Montaigne"],
  ["The universe is change; life is opinion.", "Marcus Aurelius"],
  ["When we see men of worth, we should think of equalling them; when we see men of a contrary character, we should turn inwards and examine ourselves.", "Confucius"],
  ["Nothing is miserable unless you think it so.", "Boethius"],
  ["Eat to live, and not live to eat.", "Benjamin Franklin"],
  ["Do not act as if you were going to live ten thousand years.", "Marcus Aurelius"],
  ["Never leave that till tomorrow which you can do today.", "Benjamin Franklin"],
  ["Every action you take is a vote for the type of person you wish to become.", "James Clear"],
  ["Start where you are. Use what you have. Do what you can.", "Arthur Ashe"],
  ["You must live in the present, launch yourself on every wave, find your eternity in each moment.", "Henry David Thoreau"],
  ["If you accomplish something good with hard work, the labour passes quickly, but the good endures.", "Musonius Rufus"],
  ["Nothing ever becomes real till it is experienced.", "John Keats"],
  ["Remember that to change your mind and to follow him who corrects your error is as consistent with freedom as it is to persist in your error.", "Marcus Aurelius"],
  ["First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not.", "Octavia E. Butler"],
  ["Such as are your habitual thoughts, such also will be the character of your mind; for the soul is dyed by the thoughts.", "Marcus Aurelius"],
  ["To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", "Søren Kierkegaard"],
  ["No great thing is created suddenly, any more than a bunch of grapes or a fig.", "Epictetus"],
  ["Life is long if you know how to use it.", "Seneca"],
  ["Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.", "Helen Keller"],
  ["Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.", "Zen saying"],
  ["Seize the day, and put as little trust as you can in tomorrow.", "Horace"],
  ["Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage.", "Rainer Maria Rilke"],
  ["Tell me, what is it you plan to do with your one wild and precious life?", "Mary Oliver"],
  ["Practice is the best of all instructors.", "Publilius Syrus"],
  ["Life shrinks or expands in proportion to one's courage.", "Anaïs Nin"],
  ["Reflect upon your present blessings, of which every man has plenty; not on your past misfortunes, of which all men have some.", "Charles Dickens"],
  ["Our life is frittered away by detail. Simplify, simplify.", "Henry David Thoreau"],
  ["He who is not every day conquering some fear has not learned the secret of life.", "Ralph Waldo Emerson"],
  ["If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.", "Henry David Thoreau"],
  ["Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day.", "Ralph Waldo Emerson"],
  ["Adversity has the effect of eliciting talents which in prosperous circumstances would have lain dormant.", "Horace"],
  ["Associate with those who will make a better man of you.", "Seneca"],
  ["Hatred does not cease by hatred, but only by love; this is the eternal rule.", "The Dhammapada"],
  ["Taking a new step, uttering a new word, is what people fear most.", "Fyodor Dostoevsky"],
  ["If there is no struggle, there is no progress.", "Frederick Douglass"],
  ["If you want to go fast, go alone. If you want to go far, go together.", "African proverb"],
  ["If you wish to be a good reader, read; if a writer, write.", "Epictetus"],
  ["Although the world is full of suffering, it is full also of the overcoming of it.", "Helen Keller"],
  ["If you can fill the unforgiving minute with sixty seconds' worth of distance run, yours is the Earth and everything that's in it.", "Rudyard Kipling"],
  ["Philosophy teaches us to act, not to speak.", "Seneca"],
  ["You must do the thing you think you cannot do.", "Eleanor Roosevelt"],
  ["What the superior man seeks is in himself. What the mean man seeks is in others.", "Confucius"],
  ["You could leave life right now. Let that determine what you do and say and think.", "Marcus Aurelius"],
  ["The tree which fills the arms grew from the tiniest sprout.", "Lao Tzu"],
  ["Rivers are easiest to cross at their source.", "Publilius Syrus"],
  ["Wherever there is a human being, there is an opportunity for a kindness.", "Seneca"],
  ["Even by the falling of water-drops a water-pot is filled.", "The Dhammapada"],
  ["The great thing, then, in all education, is to make our nervous system our ally instead of our enemy.", "William James"],
  ["While we are postponing, life speeds by.", "Seneca"],
  ["Plough deep while sluggards sleep, and you shall have corn to sell and to keep.", "Benjamin Franklin"],
  ["Vision without action is a daydream. Action without vision is a nightmare.", "Japanese proverb"],
  ["No act of kindness, no matter how small, is ever wasted.", "Aesop"],
  ["Never give in — never, never, never, never, in nothing great or small, large or petty.", "Winston Churchill"],
  ["The unexamined life is not worth living.", "Socrates"],
  ["Self-trust is the first secret of success.", "Ralph Waldo Emerson"],
  ["Energy and persistence conquer all things.", "Benjamin Franklin"],
  ["The most certain sign of wisdom is cheerfulness.", "Michel de Montaigne"],
  ["It is not enough to be busy; so are the ants. The question is: What are we busy about?", "Henry David Thoreau"],
  ["Do the difficult things while they are easy and do the great things while they are small.", "Lao Tzu"],
  ["It is a bad plan that admits of no modification.", "Publilius Syrus"],
  ["Dripping water hollows out a stone.", "Ovid"],
  ["Freedom is not procured by a full enjoyment of what is desired, but by controlling the desire.", "Epictetus"],
  ["Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", "Marcus Aurelius"],
  ["Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", "Langston Hughes"],
  ["The mind is not a vessel to be filled, but a fire to be kindled.", "Plutarch"],
  ["Habit is habit, and not to be flung out of the window by any man, but coaxed downstairs a step at a time.", "Mark Twain"],
  ["The sun is new each day.", "Heraclitus"],
  ["Act as if what you do makes a difference. It does.", "William James"],
  ["He suffers more than is necessary, who suffers before it is necessary.", "Seneca"],
  ["Refrain tonight, and that shall lend a kind of easiness to the next abstinence; the next more easy; for use almost can change the stamp of nature.", "William Shakespeare"],
  ["The roots of education are bitter, but the fruit is sweet.", "Aristotle"],
  ["Attention is the beginning of devotion.", "Mary Oliver"],
  ["And now that you don't have to be perfect, you can be good.", "John Steinbeck"],
  ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
  ["Great works are performed not by strength but by perseverance.", "Samuel Johnson"],
  ["They shall run, and not be weary; and they shall walk, and not faint.", "Isaiah 40:31"],
  ["I examine my entire day and go back over what I have done and said, hiding nothing from myself, passing nothing by.", "Seneca"],
  ["If you want to improve, be content to be thought foolish and stupid.", "Epictetus"],
  ["Knowing others is intelligence; knowing yourself is true wisdom.", "Lao Tzu"],
  ["Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", "Marcus Aurelius"],
  ["Anyone can become angry — that is easy. But to be angry with the right person, to the right degree, at the right time, for the right purpose, and in the right way — that is not easy.", "Aristotle"],
  ["First say to yourself what you would be; and then do what you have to do.", "Epictetus"],
  ["When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.", "Confucius"],
  ["The greatest thing in the world is to know how to belong to oneself.", "Michel de Montaigne"],
  ["Kind words do not cost much. Yet they accomplish much.", "Blaise Pascal"],
  ["I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", "Bruce Lee"],
  ["He who knows that enough is enough will always have enough.", "Lao Tzu"],
  ["I hated every minute of training, but I said, \"Don't quit. Suffer now and live the rest of your life as a champion.\"", "Muhammad Ali"],
  ["Treat people as if they were what they ought to be, and you help them to become what they are capable of being.", "Johann Wolfgang von Goethe"],
  ["He that can have patience can have what he will.", "Benjamin Franklin"],
  ["Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.", "Marcus Aurelius"],
  ["Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"],
  ["Gratitude is not only the greatest of virtues, but the parent of all the others.", "Cicero"],
  ["Know, first, who you are, and then adorn yourself accordingly.", "Epictetus"],
  ["Life can only be understood backwards; but it must be lived forwards.", "Søren Kierkegaard"],
  ["No man is free who is not master of himself.", "Epictetus"],
  ["Nowhere can man find a quieter or more untroubled retreat than in his own soul.", "Marcus Aurelius"],
  ["Energy is eternal delight.", "William Blake"],
  ["How long are you going to wait before you demand the best for yourself?", "Epictetus"],
  ["Resolve to perform what you ought; perform without fail what you resolve.", "Benjamin Franklin"],
  ["Things do not change; we change.", "Henry David Thoreau"],
  ["Do not disturb yourself by thinking of the whole of your life.", "Marcus Aurelius"],
  ["We become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts.", "Aristotle"],
  ["All shall be well, and all shall be well, and all manner of thing shall be well.", "Julian of Norwich"],
  ["As rain breaks through an ill-thatched house, passion will break through an unreflecting mind.", "The Dhammapada"],
  ["Love the art, poor as it may be, which you have learned, and be content with it.", "Marcus Aurelius"],
  ["When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor Frankl"],
  ["Take away your opinion, and there is taken away the complaint, \"I have been harmed.\" Take away the complaint, and the harm is taken away.", "Marcus Aurelius"],
  ["If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", "Martin Luther King Jr."],
  ["He who conquers others is strong; he who conquers himself is mighty.", "Lao Tzu"],
  ["Fall seven times, stand up eight.", "Japanese proverb"],
  ["Be patient and tough; someday this pain will be useful to you.", "Ovid"],
  ["It may be that when we no longer know what to do we have come to our real work.", "Wendell Berry"],
  ["The best way of avenging thyself is not to become like the wrongdoer.", "Marcus Aurelius"],
  ["Sometimes even to live is an act of courage.", "Seneca"],
  ["Heaven is under our feet as well as over our heads.", "Henry David Thoreau"],
  ["Fire tests gold, suffering tests brave men.", "Seneca"],
  ["Nothing is softer or more flexible than water, yet nothing can resist it.", "Lao Tzu"],
  ["No man is free who is a slave to his body.", "Seneca"],
  ["How poor are they that have not patience! What wound did ever heal but by degrees?", "William Shakespeare"],
  ["It is quality rather than quantity that matters.", "Seneca"],
  ["There is nothing either good or bad, but thinking makes it so.", "William Shakespeare"],
  ["The whole future lies in uncertainty: live immediately.", "Seneca"],
  ["With the past, I have nothing to do; nor with the future. I live now.", "Ralph Waldo Emerson"],
  ["Temperance: eat not to dullness; drink not to elevation.", "Benjamin Franklin"],
  ["Remember that you are an actor in a drama, of such a kind as the author pleases to make it.", "Epictetus"],
  ["The superior man is modest in his speech, but exceeds in his actions.", "Confucius"],
  ["As iron sharpeneth iron, so a man sharpeneth the countenance of his friend.", "Proverbs 27:17"],
  ["Though one should conquer a thousand times a thousand men in battle, he who conquers himself is the greatest of victors.", "The Dhammapada"],
  ["Well done is better than well said.", "Benjamin Franklin"],
  ["All that we are is the result of what we have thought.", "The Dhammapada"],
  ["Diligence is the mother of good luck.", "Benjamin Franklin"],
  ["Do every act of your life as though it were the very last act of your life.", "Marcus Aurelius"],
  ["Difficulties strengthen the mind, as labour does the body.", "Seneca"],
  ["Men exist for the sake of one another. Teach them then or bear with them.", "Marcus Aurelius"],
  ["Seek not that the things which happen should happen as you wish; but wish the things which happen to be as they are, and you will have a tranquil flow of life.", "Epictetus"],
  ["Better than a thousand hollow words is one word that brings peace.", "The Dhammapada"],
  ["It is not the man who has too little, but the man who craves more, that is poor.", "Seneca"],
  ["Walk as if you are kissing the Earth with your feet.", "Thich Nhat Hanh"],
  ["Whatever happens at all happens as it should.", "Marcus Aurelius"],
  ["Adopt the pace of nature: her secret is patience.", "Ralph Waldo Emerson"],
  ["Every habit and faculty is maintained and increased by the corresponding actions.", "Epictetus"],
  ["Loss is nothing else but change, and change is Nature's delight.", "Marcus Aurelius"],
  ["Nothing will ever be attempted if all possible objections must be first overcome.", "Samuel Johnson"],
  ["We must learn to reawaken and keep ourselves awake, not by mechanical aids, but by an infinite expectation of the dawn.", "Henry David Thoreau"],
  ["If anyone tells you that a certain person speaks ill of you, do not make excuses, but answer: \"He was ignorant of my other faults, else he would not have mentioned these alone.\"", "Epictetus"],
  ["When you have been compelled by circumstances to be disturbed, quickly return to yourself.", "Marcus Aurelius"],
  ["Alone we can do so little; together we can do so much.", "Helen Keller"],
  ["Receive without pride, let go without struggle.", "Marcus Aurelius"],
  ["The best is the enemy of the good.", "Voltaire"],
  ["Adapt yourself to the things among which your lot has been cast.", "Marcus Aurelius"],
  ["Great things are done by a series of small things brought together.", "Vincent van Gogh"],
  ["Hope is itself a species of happiness, and, perhaps, the chief happiness which this world affords.", "Samuel Johnson"],
  ["I am not afraid of storms, for I am learning how to sail my ship.", "Louisa May Alcott"],
  ["Let us not be weary in well doing: for in due season we shall reap, if we faint not.", "Galatians 6:9"],
  ["A cucumber is bitter. Throw it away. There are briars in the road. Turn aside from them. This is enough.", "Marcus Aurelius"],
  ["Little things console us because little things afflict us.", "Blaise Pascal"],
  ["The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"],
  ["Write it on your heart that every day is the best day in the year.", "Ralph Waldo Emerson"],
  ["Learning without thought is labour lost; thought without learning is perilous.", "Confucius"],
  ["How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"],
  ["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
  ["You are the sky. Everything else — it's just the weather.", "Pema Chödrön"],
  ["The softest things in the world overcome the hardest things in the world.", "Lao Tzu"],
  ["I am the master of my fate, I am the captain of my soul.", "William Ernest Henley"],
  ["Difficulties are things that show a person what they are.", "Epictetus"],
  ["However mean your life is, meet it and live it; do not shun it and call it hard names.", "Henry David Thoreau"],
  ["I am still learning.", "Michelangelo"],
  ["Knowing is not enough; we must apply. Willing is not enough; we must do.", "Johann Wolfgang von Goethe"],
  ["It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"],
  ["If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.", "Marcus Aurelius"],
  ["Only that day dawns to which we are awake.", "Henry David Thoreau"],
  ["I count him braver who overcomes his desires than him who conquers his enemies.", "Aristotle"],
  ["No one can construct for you the bridge upon which precisely you must cross the stream of life, no one but you yourself alone.", "Friedrich Nietzsche"],
  ["Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"],
  ["The most common form of despair is not being who you are.", "Søren Kierkegaard"],
  ["\"Hope\" is the thing with feathers — that perches in the soul.", "Emily Dickinson"],
  ["Rather than love, than money, than fame, give me truth.", "Henry David Thoreau"],
  ["Let us prepare our minds as if we had come to the very end of life. Let us postpone nothing.", "Seneca"],
  ["Practise yourself, for heaven's sake, in little things; and thence proceed to greater.", "Epictetus"],
  ["The best time to plant a tree was twenty years ago. The second best time is now.", "Proverb"],
  ["What you do not want done to yourself, do not do to others.", "Confucius"],
  ["Do not let what you cannot do interfere with what you can do.", "John Wooden"],
  ["The invariable mark of wisdom is to see the miraculous in the common.", "Ralph Waldo Emerson"],
  ["Never measure the height of a mountain until you have reached the top. Then you will see how low it was.", "Dag Hammarskjöld"],
  ["The chains of habit are too weak to be felt until they are too strong to be broken.", "Samuel Johnson"],
  ["A merry heart doeth good like a medicine.", "Proverbs 17:22"],
  ["Dost thou love life? Then do not squander time, for that's the stuff life is made of.", "Benjamin Franklin"],
  ["To every thing there is a season, and a time to every purpose under the heaven.", "Ecclesiastes 3:1"],
  ["Hold every hour in your grasp. Lay hold of today's task, and you will not need to depend so much upon tomorrow's.", "Seneca"],
  ["Nothing can be more useful to a man than a determination not to be hurried.", "Henry David Thoreau"],
  ["What it lies in our power to do, it lies in our power not to do.", "Aristotle"],
  ["At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work — as a human being.", "Marcus Aurelius"],
  ["Not being able to govern events, I govern myself.", "Michel de Montaigne"],
  ["Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", "Mother Teresa"],
  ["True joy is a serious thing.", "Seneca"],
  ["Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson"],
  ["In every walk with nature one receives far more than he seeks.", "John Muir"],
  ["If a man knows not to which port he sails, no wind is favorable.", "Seneca"],
  ["Nothing is worth more than this day.", "Johann Wolfgang von Goethe"],
  ["Whatsoever thy hand findeth to do, do it with thy might.", "Ecclesiastes 9:10"],
  ["Few things are impossible to diligence and skill.", "Samuel Johnson"],
  ["The first and best of victories is for a man to conquer himself.", "Plato"],
  ["One must still have chaos in oneself to be able to give birth to a dancing star.", "Friedrich Nietzsche"],
  ["Habit is overcome by habit.", "Thomas à Kempis"],
  ["The greatest remedy for anger is delay.", "Seneca"],
  ["Your pain is the breaking of the shell that encloses your understanding.", "Kahlil Gibran"],
  ["The two most powerful warriors are patience and time.", "Leo Tolstoy"],
  ["Every day should be regulated as if it closed the series, as if it rounded out and completed our existence.", "Seneca"],
  ["A happy life consists in tranquility of mind.", "Cicero"],
  ["He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", "Epictetus"],
  ["It is one of the blessings of old friends that you can afford to be stupid with them.", "Ralph Waldo Emerson"],
  ["Wisely and slow; they stumble that run fast.", "William Shakespeare"],
  ["The body should be treated more rigorously, that it may not be disobedient to the mind.", "Seneca"],
  ["Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.", "William Shakespeare"],
  ["Trust thyself: every heart vibrates to that iron string.", "Ralph Waldo Emerson"],
  ["He who binds to himself a joy does the winged life destroy; but he who kisses the joy as it flies lives in eternity's sunrise.", "William Blake"],
  ["Keep silence for the most part, and speak only when you must, and then briefly.", "Epictetus"],
  ["The best way out is always through.", "Robert Frost"],
  ["When I dance, I dance; when I sleep, I sleep.", "Michel de Montaigne"],
  ["What does not destroy me, makes me stronger.", "Friedrich Nietzsche"],
  ["Character — the willingness to accept responsibility for one's own life — is the source from which self-respect springs.", "Joan Didion"],
  ["Nothing is at last sacred but the integrity of your own mind.", "Ralph Waldo Emerson"],
  ["I know of no more encouraging fact than the unquestionable ability of man to elevate his life by conscious endeavor.", "Henry David Thoreau"],
  ["Nothing happens to any man which he is not formed by nature to bear.", "Marcus Aurelius"],
  ["I went to the woods because I wished to live deliberately.", "Henry David Thoreau"],
  ["Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"],
  ["It is impossible for a man to learn what he thinks he already knows.", "Epictetus"],
  ["Courage is resistance to fear, mastery of fear — not absence of fear.", "Mark Twain"],
  ["Some things are within our power, while others are not.", "Epictetus"],
  ["To wish to be well is a part of becoming well.", "Seneca"],
  ["He who is contented is rich.", "Lao Tzu"],
  ["Go to the ant, thou sluggard; consider her ways, and be wise.", "Proverbs 6:6"],
  ["If you hear a voice within you say \"you cannot paint,\" then by all means paint, and that voice will be silenced.", "Vincent van Gogh"],
  ["The part of life we really live is small. For all the rest of existence is not life, but merely time.", "Seneca"],
  ["Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances.", "Viktor Frankl"],
  ["How much more grievous are the consequences of anger than the causes of it.", "Marcus Aurelius"],
  ["Retire into yourself as much as you can.", "Seneca"],
  ["Life is either a daring adventure, or nothing.", "Helen Keller"],
  ["Nothing will work unless you do.", "Maya Angelou"],
  ["He who has begun has half done. Dare to be wise; begin!", "Horace"],
  ["Great acts are made up of small deeds.", "Lao Tzu"],
  ["Not everything that is faced can be changed, but nothing can be changed until it is faced.", "James Baldwin"],
  ["Perfection of character is this: to live each day as if it were your last, without frenzy, without apathy, without pretence.", "Marcus Aurelius"],
  ["Whatever can happen at any time can happen today.", "Seneca"],
  ["It is not so much our friends' help that helps us, as the confidence of their help.", "Epicurus"],
  ["Most powerful is he who has himself in his own power.", "Seneca"],
  ["Instructions for living a life: Pay attention. Be astonished. Tell about it.", "Mary Oliver"],
  ["Motivation is what gets you started. Habit is what keeps you going.", "Jim Rohn"],
  ["The value of life lies not in the length of days, but in the use we make of them.", "Michel de Montaigne"],
  ["Man lives only in the present, in this fleeting instant; all the rest of his life is either past and gone, or not yet revealed.", "Marcus Aurelius"],
  ["The time is always right to do what is right.", "Martin Luther King Jr."],
  ["This time, like all times, is a very good one, if we but know what to do with it.", "Ralph Waldo Emerson"],
  ["Happiness depends upon ourselves.", "Aristotle"],
  ["Re-examine all you have been told at school or church or in any book, dismiss whatever insults your own soul.", "Walt Whitman"],
  ["Let a man overcome anger by love, let him overcome evil by good.", "The Dhammapada"],
  ["Think of yourself as dead. You have lived your life. Now take what's left and live it properly.", "Marcus Aurelius"],
  ["In the long run, men hit only what they aim at.", "Henry David Thoreau"],
  ["Time is a sort of river of passing events, and strong is its current.", "Marcus Aurelius"],
  ["It is not he who reviles or strikes you who insults you, but your opinion that these things are insulting.", "Epictetus"],
  ["The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", "Marcus Aurelius"],
  ["I exist as I am, that is enough.", "Walt Whitman"],
  ["Let not your mind run on what you lack as much as on what you have already.", "Marcus Aurelius"],
  ["All things excellent are as difficult as they are rare.", "Baruch Spinoza"],
  ["Well-being is attained little by little, and nevertheless is no little thing itself.", "Zeno of Citium"],
  ["Nothing ever goes away until it has taught us what we need to know.", "Pema Chödrön"],
  ["Love all, trust a few, do wrong to none.", "William Shakespeare"],
  ["Only the educated are free.", "Epictetus"],
  ["The art of living is more like wrestling than dancing.", "Marcus Aurelius"],
  ["I dwell in Possibility.", "Emily Dickinson"],
  ["The mind that is anxious about future events is miserable.", "Seneca"],
  ["Do the thing we fear, and the death of fear is certain.", "Ralph Waldo Emerson"],
  ["One ought, every day at least, to hear a little song, read a good poem, see a fine picture, and, if it were possible, to speak a few reasonable words.", "Johann Wolfgang von Goethe"],
  ["Lost time is never found again.", "Benjamin Franklin"],
  ["Little by little, one goes far.", "Spanish proverb"],
  ["Our strength grows out of our weakness.", "Ralph Waldo Emerson"],
  ["All of humanity's problems stem from man's inability to sit quietly in a room alone.", "Blaise Pascal"],
  ["The world breaks every one and afterward many are strong at the broken places.", "Ernest Hemingway"],
  ["The mystery of human existence lies not in just staying alive, but in finding something to live for.", "Fyodor Dostoevsky"],
  ["No man ever steps in the same river twice.", "Heraclitus"],
  ["Order: let all your things have their places; let each part of your business have its time.", "Benjamin Franklin"],
  ["Whatever you would make habitual, practise it; and if you would not make a thing habitual, do not practise it, but accustom yourself to something else.", "Epictetus"],
  ["Well begun is half done.", "Aristotle"],
  ["I will not be concerned at men's not knowing me; I will be concerned at my own want of ability.", "Confucius"],
  ["There is no greatness where there is not simplicity, goodness, and truth.", "Leo Tolstoy"],
  ["Absorb what is useful, discard what is useless, add what is specifically your own.", "Bruce Lee"],
  ["Be patient toward all that is unsolved in your heart and try to love the questions themselves.", "Rainer Maria Rilke"],
  ["Always bear in mind that your own resolution to succeed is more important than any other one thing.", "Abraham Lincoln"],
  ["Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", "Theodore Roosevelt"],
  ["Whoever is happy will make others happy too.", "Anne Frank"],
  ["To strive, to seek, to find, and not to yield.", "Alfred, Lord Tennyson"],
  ["Wish not so much to live long as to live well.", "Benjamin Franklin"],
  ["The present moment is filled with joy and happiness. If you are attentive, you will see it.", "Thich Nhat Hanh"],
  ["Is virtue a thing remote? I wish to be virtuous, and lo! virtue is at hand.", "Confucius"],
  ["Nothing is so fatiguing as the eternal hanging on of an uncompleted task.", "William James"],
  ["The cost of a thing is the amount of what I will call life which is required to be exchanged for it.", "Henry David Thoreau"],
  ["It is a rough road that leads to the heights of greatness.", "Seneca"],
  ["Be joyful though you have considered all the facts.", "Wendell Berry"],
  ["Men are disturbed not by the things which happen, but by the opinions about the things.", "Epictetus"],
  ["Every morning was a cheerful invitation to make my life of equal simplicity, and I may say innocence, with Nature herself.", "Henry David Thoreau"],
  ["Little by little does the trick.", "Aesop"],
  ["Just that you do the right thing. The rest doesn't matter.", "Marcus Aurelius"],
  ["Let us, then, be up and doing, with a heart for any fate; still achieving, still pursuing, learn to labor and to wait.", "Henry Wadsworth Longfellow"]
];
